spring.application.name=gateway
server.port=8888

# JWT (même secret que le service Utilisateur)
app.jwt.secret=1234567890123456789012345678901234567890123456789012345678901234


# Routes vers vos services
spring.cloud.gateway.routes[0].id=utilisateur-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/gestion/**

spring.cloud.gateway.routes[1].id=livre-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/gestionlivre/**

spring.cloud.gateway.routes[2].id=emprunt-service
spring.cloud.gateway.routes[2].uri=http://localhost:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/gestionemprunt/**

spring.cloud.gateway.routes[3].id=penalite-service
spring.cloud.gateway.routes[3].uri=http://localhost:8085
spring.cloud.gateway.routes[3].predicates[0]=Path=/gestionpenalite/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/gestionnotification/**