spring.application.name=penalite
# application.properties


# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_penalites?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.servlet.context-path=/gestionpenalite
# Server port
server.port=8085

# Eureka (désactivé pour tester)
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Penalty Configuration
penalite.tarif-par-jour=0.50
penalite.plafond-max=20.00
penalite.jours-grace=0

# Logging
logging.level.com.bibliotheque.penalite=DEBUG
